<div id="rev_slider_632_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="websitebuilder-slider1" style="margin:0px auto;background-color:#000000;padding:0px;margin-top:0px;margin-bottom:0px;">
        <!-- START REVOLUTION SLIDER 5.3.0 fullwidth mode -->
        <div id="rev_slider_632_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.3.0">
            <ul>
                <!-- SLIDE  -->
                <li data-index="rs-1904" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="../../assets/images/slidebg1-100x50.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="layout/element/images/carrucel2/fondo.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="5" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-13" id="slide-1904-layer-3" data-x="['left','left','left','left']" data-hoffset="['-77','-186','-156','-137']" data-y="['top','top','top','top']" data-voffset="['51','51','74','102']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-200px;y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;" data-transform_out="auto:auto;s:1000;e:Power2.easeInOut;" data-start="500" data-responsive_offset="on" style="z-index: 5;"><img src="layout/element/images/carrucel2/Archer.png" alt="" width="300" height="400" data-ww="['450px','300px','250px','200px']" data-hh="['550px','400px','333px','267px']" data-no-retina> </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-7" id="slide-1904-layer-4" data-x="['left','left','left','left']" data-hoffset="['844','738','547','288']" data-y="['top','top','top','top']" data-voffset="['-10','-118','-77','-67']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:200px;y:bottom;rZ:-45deg;s:1500;e:Power4.easeOut;" data-transform_out="auto:auto;s:1000;e:Power2.easeInOut;" data-start="750" data-responsive_offset="on" style="z-index: 6;"><img src="layout/element/images/l2logo.png" alt="" width="400" height="400" data-ww="['300px','400px','300px','280px']" data-hh="['100px','400px','100px','280px']" data-no-retina> </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-5" id="slide-1904-layer-5" data-x="['left','left','left','left']" data-hoffset="['990','898','691','412']" data-y="['top','top','top','top']" data-voffset="['294','320','291','309']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:100px;y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;" data-transform_out="auto:auto;s:1000;e:Power2.easeInOut;" data-start="1000" data-responsive_offset="on" style="z-index: 7;"><img src="layout/element/images/carrucel2/mob.png" alt="" width="240" height="450" data-ww="['400px','240px','180px','200px']" data-hh="['450px','450px','338px','375px']" data-no-retina> </div>


                    <!-- LAYER NR. 5 -->
                    <div class="tp-caption  " id="slide-1904-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-40','-60','-60','-70']" data-fontsize="['50','50','40','30']" data-lineheight="['50','50','40','30']" data-width="['none','640','380','320']" data-height="none" data-whitespace="['nowrap','normal','normal','normal']" data-transform_idle="o:1;" data-transform_in="y:20px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-20px;opacity:0;s:300;e:Power2.easeInOut;" data-start="250" data-splitin="none" data-splitout="none" data-responsive_offset="off" data-responsive="off" style="z-index: 9; white-space: nowrap; font-size: 50px; line-height: 50px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family:Lato;text-align:center;">Panel De Usuarios </div>

                    <!-- LAYER NR. 6 -->
                    <div class="tp-caption  " id="slide-1904-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['11','16','20','14']" data-width="['none','640','380','320']" data-height="none" data-whitespace="['nowrap','normal','normal','normal']" data-transform_idle="o:1;" data-transform_in="y:20px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-20px;opacity:0;s:300;e:Power2.easeInOut;" data-start="300" data-splitin="none" data-splitout="none" data-responsive_offset="off" data-responsive="off" style="z-index: 10; white-space: nowrap; font-size: 20px; line-height: 25px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Lato;text-align:center;">Sistema completo para la administracion de los usuarios y las conaciones</div>

                    <!-- LAYER NR. 7 -->
                    <a class="tp-caption rev-btn " href="{!! URL::to('lineage2-panel-usuario') !!}" target="_blank" id="slide-1904-layer-8" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['82','87','103','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:150;e:Power1.easeInOut;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(255, 255, 255, 0);bc:rgba(255, 255, 255, 1.00);" data-transform_in="y:10px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-10px;opacity:0;s:300;e:Power2.easeInOut;" data-start="350" data-splitin="none" data-splitout="none" data-actions='' data-responsive_offset="off" data-responsive="off" style="z-index: 11; white-space: nowrap; font-size: 16px; line-height: 42px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Lato;background-color:rgba(240, 69, 49, 1.00);padding:0px 28px 0px 28px;border-color:rgba(240, 69, 49, 1.00);border-style:solid;border-width:2px;border-radius:3px 3px 3px 3px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Ver Mas</a>
                </li>
                <!-- SLIDE  -->
                <li data-index="rs-1905" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="../../assets/images/slidebg6-100x50.jpg" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <!-- MAIN IMAGE -->
                    <img src="layout/element/images/carrucel2/fondo1.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="5" class="rev-slidebg" data-no-retina>
                    <!-- LAYERS -->

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-13" id="slide-1905-layer-3" data-x="['left','left','left','left']" data-hoffset="['27','-70','-54','-121']" data-y="['top','top','top','top']" data-voffset="['39','43','13','23']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-200px;y:bottom;rZ:45deg;s:1500;e:Power4.easeOut;" data-transform_out="auto:auto;s:1000;e:Power2.easeInOut;" data-start="500" data-responsive_offset="on" style="z-index: 5;"><img src="layout/element/images/carrucel2/belhet.png" alt="" width="210" height="190" data-ww="['400px','210','210px','210px']" data-hh="['600px','190','190px','190px']" data-no-retina> </div>

                    <!-- LAYER NR. 2 -->
                    <div class="tp-caption   tp-resizeme rs-parallaxlevel-7" id="slide-1905-layer-4" data-x="['left','left','left','left']" data-hoffset="['1033','874','637','376']" data-y="['top','top','top','top']" data-voffset="['271','291','295','330']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:200px;y:bottom;rZ:-45deg;s:1500;e:Power4.easeOut;" data-transform_out="auto:auto;s:1000;e:Power2.easeInOut;" data-start="750" data-responsive_offset="on" style="z-index: 6;"><img src="layout/element/images/carrucel2/axe.png" alt="" width="140" height="170" data-ww="['250px','140','140px','140px']" data-hh="['240','170','170px','170px']" data-no-retina> </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption  " id="slide-1905-layer-1" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['-40','-60','-60','-70']" data-fontsize="['50','50','40','30']" data-lineheight="['50','50','40','30']" data-width="['none','640','380','320']" data-height="none" data-whitespace="['nowrap','normal','normal','normal']" data-transform_idle="o:1;" data-transform_in="y:20px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-20px;opacity:0;s:300;e:Power2.easeInOut;" data-start="250" data-splitin="none" data-splitout="none" data-responsive_offset="off" data-responsive="off" style="z-index: 7; white-space: nowrap; font-size: 50px; line-height: 50px; font-weight: 900; color: rgba(255, 255, 255, 1.00);font-family:Lato;text-align:center;">Panel de Admin</div>

                    <!-- LAYER NR. 4 -->
                    <div class="tp-caption  " id="slide-1905-layer-2" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['11','16','20','14']" data-width="['none','640','380','320']" data-height="none" data-whitespace="['nowrap','normal','normal','normal']" data-transform_idle="o:1;" data-transform_in="y:20px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-20px;opacity:0;s:300;e:Power2.easeInOut;" data-start="300" data-splitin="none" data-splitout="none" data-responsive_offset="off" data-responsive="off" style="z-index: 8; white-space: nowrap; font-size: 20px; line-height: 25px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Lato;text-align:center;">Panel diseñado para simplificar la vida a los Administradores</div>

                    <!-- LAYER NR. 5 -->
                    <a class="tp-caption rev-btn   tp-rs-menulink" href="{!! URL::to('lineage2-panel-admin') !!}" target="_self" id="slide-1905-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['82','87','103','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_hover="o:1;rX:0;rY:0;rZ:0;z:0;s:150;e:Power1.easeInOut;" data-style_hover="c:rgba(255, 255, 255, 1.00);bg:rgba(255, 255, 255, 0);bc:rgba(255, 255, 255, 1.00);" data-transform_in="y:10px;opacity:0;s:800;e:Power4.easeOut;" data-transform_out="y:-10px;opacity:0;s:300;e:Power2.easeInOut;" data-start="350" data-splitin="none" data-splitout="none" data-actions='' data-responsive_offset="off" data-responsive="off" style="z-index: 9; white-space: nowrap; font-size: 16px; line-height: 42px; font-weight: 700; color: rgba(255, 255, 255, 1.00);font-family:Lato;background-color:rgba(240, 69, 49, 1.00);padding:0px 28px 0px 28px;border-color:rgba(240, 69, 49, 1.00);border-style:solid;border-width:2px;border-radius:3px 3px 3px 3px;outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;">Ver Mas </a>
                </li>
            </ul>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
        </div>
    </div>